/******************************************************************************/
//
// This file was generated by OSAcfg_Tool utility.
// Do not modify it to prevent data loss on next editing.
//
// PROJECT NAME: pic18_RTOS
//
// PLATFORM:     Microchip C18
//
/******************************************************************************/


#ifndef _OSACFG_H
#define _OSACFG_H

//------------------------------------------------------------------------------
// SYSTEM
//------------------------------------------------------------------------------

#define OS_TASKS                3   // Number of tasks that can be active at one time


//------------------------------------------------------------------------------
// ENABLE CONSTANTS
//------------------------------------------------------------------------------
#define OS_DISABLE_PRIORITY
#define OS_ENABLE_TTIMERS          // Enable task timers (allows to use OS_Delay and OS_xxx_Wait_TO)




#endif
